
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
 branches:
   include:
     - develop
     - qa
 paths:
  exclude:
    - '**/*.yml'
    - '**/*.yaml'
    - readme.md

variables:
  - name: environmentName
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
      value: 'dev'
    ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/qa') }}:
      value: 'qa'

# variables:
#   - name: colour
#     ${{ if eq( parameters['environment'], 'develop') }}:
#       value: "red"
#     ${{ elseif eq( parameters['environment'], 'preproduction' ) }}:
#       value: "yellow"
#     ${{ else }}:
#       value: "purple"



jobs:
- deployment: ValidateAndDeployment
  displayName: Validate and deployment
  pool:
    vmImage: ubuntu-latest
  environment: 
   name: $(environmentName)
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          clean: true
          fetchDepth: full
          persistCredentials: true
        - task: NodeTool@0 
          inputs:
            versionSpec: '16.x'
        - task: DownloadSecureFile@1
          name: SalesforceToken
          displayName: 'Download auth file for SFDX'
          inputs:
            secureFile: $(environmentName)Token.json
        - script: |
            echo "*******SOURCE_BRANCH_NAME****************"
            sourceBranch=$(echo "$BRANCH_NAME" | sed 's|refs/heads/||g')
            echo "##vso[task.setvariable variable=sourceBranch;]$sourceBranch"
            echo "$sourceBranch"
            echo "*****************************************"
            curl -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" -X GET -L "https://dev.azure.com/suvam1999roy/Azure%20Devops%20Test/_apis/build/latest/$(System.DefinitionId)?branchName=$sourceBranch&api-version=7.0-preview.1" -o sourceVersionResponse.json
            echo "************************"
            cat sourceVersionResponse.json
            echo "************************"
            if cat sourceVersionResponse.json | grep -o '"result":"[^"]*' | grep -o '[^"]*$' | grep -q succeeded; then
              latestBuildCommit=$(cat sourceVersionResponse.json | grep -o '"sourceVersion":"[^"]*' | grep -o '[^"]*$')
              echo "Last build succeeded, commit set to latest deployed to environment: $latestBuildCommit"
              echo "##vso[task.setvariable variable=latestBuildCommit]$latestBuildCommit"
            else
              latestBuildCommit=$(git rev-list --all --max-parents=0)
              echo "Last build failed or error, commit set to initial one from branch $BRANCH_NAME and its $latestBuildCommit"
              echo "##vso[task.setvariable variable=latestBuildCommit]$latestBuildCommit"
            fi
          displayName: "Download latest build commit for environment"
          env:
              BRANCH_NAME: $(Build.SourceBranchName)
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        - script: |
            if ! command -v sfdx &> /dev/null
              then
                  echo "SFDX Not found, installing..."
                  npm install -g sfdx-cli --loglevel verbose
                  echo y | sfdx plugins:install sfdx-git-delta
                  echo y | sfdx plugins:install @salesforce/sfdx-scanner
              else
                  echo "SFDX installed."
            fi
          displayName: "Install SFDX and SDG"
        - script: |
            sfdx auth:sfdxurl:store -f $(SalesforceToken.secureFilePath) -a $(environmentName)
          displayName: "Salesforce Login"
        - script: |
            sfdx sgd:source:delta --to HEAD --from $(latestBuildCommit) -o .
            mv package/package.xml manifest/package.xml
            echo "*********PACKAGE.XML******************"
            cat manifest/package.xml
            echo "**************************************"
          displayName: "Create a Manifest"
        - script: |
            if [ $(runTestClasses) = "true" ]; then
              echo "runTestClasses variable set to true, running build with test classes"
              sfdx force:source:deploy -l RunLocalTests -x manifest/package.xml --targetusername $(environmentName)
            else
              sfdx force:source:deploy -x manifest/package.xml --targetusername $(environmentName)
            fi
          displayName: "Deploy to environment"
        - script: |
            if [ $(environmentName) = "PROD" ]; then
              ver="$(environmentName)-$(date '+%d-%m-%Y-%H-%M')"
              echo "Deployment to $(environmentName), creating and pushing TAG $ver"
              git tag "$ver"
              git push origin "$ver"
            else
              echo "Nothing to tag"
            fi

          displayName: "Create TAG for succesfull release"