
@IsTest
private class ValidServiceTest {
    @IsTest
    static void myUnitTest() {
        // TO DO: implement unit test
        ValidService.printWelcomeMessage();
        System.debug('Welcome to PwC');
        System.debug('Welcome to PwC');
        System.debug('Welcome to PwC');
        System.debug('Welcome to PwC');
        System.debug('Welcome to PwC');
        System.debug('Welcome to PwC');
        System.debug('New feature 1');
        System.debug('New feature 1');
        System.debug('New develop feature 1');
        System.debug('New develop feature 2');
        System.debug('New develop feature 3');
        System.debug('New develop feature 4');
        System.debug('New develop feature 5');
        System.debug('New develop feature 6');
        System.debug('New develop feature 6');
        System.debug('New develop feature 7');
        System.debug('New develop feature 8');
        System.debug('New develop feature 9');
        System.debug('New develop feature 10');
    }
}
