public with sharing class WelcomeToPwC {
    // public WelcomeToPwC() {

    // }

    public static void printWelcomeMessage() {
        System.debug('Welcome to PwC');
        System.debug('Welcome to PwC');
        System.debug('Welcome to PwC');
        System.debug('Welcome to PwC');
        System.debug('Welcome to PwC');
        System.debug('Welcome to PwC');
        System.debug('New feature 1');
        System.debug('New feature 1');
    }
}